### ISSUE TITLE
Calendar is marking wrong cell as today

### ISSUE THREAD

**Issue by joelalejandro** [SomosCodear/codear-site#16]
![image](https://user-images.githubusercontent.com/118913/72019138-da044080-3247-11ea-929a-552cd6279e63.png)

**Comment by homer0** [comment]
@asermax I only had 15min to debug it (sorry!), but I think I know where it comes from: This is like the clock bug we had last year, the static file was generated on that day, so it comes highlighted "from the server"; the difference here is that the hydration is not working how it should.

Try this: open the calendar, move to last december and then back to january, you'll see that the highlight doesn't change, even when it shows the right date, they are both highlighted. It gets fixed when you move to a month with less than 31 days.

I checked the component and I didn't see any "optimization" (memo/pure/cache/whatever) for how the days are rendered... and that's all the time I had.

**Comment by asermax** [comment]
I think it has to do with a hydration mismatch. I was able to reproduce the issue (kinda) locally by making the server render be different than the client render, which gave a class mismatch error and, for some reason, instead of giving priority to the client rendered result it gave priority to the SSR rendered one.
I'll try to make the current day highlight be delayed until the component is mounted, so we don't have this conflict.
